
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

interface CountryFlagProps {
  country: string;
  className?: string;
}

const countryCodeMapping: { [key: string]: string } = {
  "England": "gb-eng",
  "Spain": "es",
  "Germany": "de",
  "Italy": "it",
  "France": "fr",
  "Netherlands": "nl",
  "Portugal": "pt",
  "USA": "us",
  "Brazil": "br",
  "Scotland": "gb-sct",
  "Australia": "au",
  "Japan": "jp",
  "Turkey": "tr",
  "Russia": "ru",
  "Argentina": "ar",
  "Mexico": "mx",
  "Belgium": "be",
  "Greece": "gr",
  "Norway": "no",
  "Sweden": "se",
  "Denmark": "dk",
  "Poland": "pl",
  "Czech Republic": "cz",
  "Austria": "at",
  "Switzerland": "ch",
  "Croatia": "hr",
  "Serbia": "rs",
  "Ukraine": "ua",
  "Romania": "ro",
  "Bulgaria": "bg",
  "Hungary": "hu",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Bosnia and Herzegovina": "ba",
  "North Macedonia": "mk",
  "Montenegro": "me",
  "Albania": "al",
  "Moldova": "md",
  "Lithuania": "lt",
  "Latvia": "lv",
  "Estonia": "ee",
  "Finland": "fi",
  "Iceland": "is",
  "Ireland": "ie",
  "Northern Ireland": "gb-nir",
  "Wales": "gb-wls",
  "Israel": "il",
  "Cyprus": "cy",
  "Malta": "mt",
  "Luxembourg": "lu",
  "Liechtenstein": "li",
  "Andorra": "ad",
  "San Marino": "sm",
  "Monaco": "mc",
  "Vatican City": "va",
  "Canada": "ca",
  "Colombia": "co",
  "Peru": "pe",
  "Chile": "cl",
  "Uruguay": "uy",
  "Paraguay": "py",
  "Bolivia": "bo",
  "Ecuador": "ec",
  "Venezuela": "ve",
  "Guyana": "gy",
  "Suriname": "sr",
  "French Guiana": "gf",
  "South Korea": "kr",
  "North Korea": "kp",
  "China": "cn",
  "India": "in",
  "Thailand": "th",
  "Vietnam": "vn",
  "Indonesia": "id",
  "Malaysia": "my",
  "Singapore": "sg",
  "Philippines": "ph",
  "Myanmar": "mm",
  "Cambodia": "kh",
  "Laos": "la",
  "Brunei": "bn",
  "Taiwan": "tw",
  "Hong Kong": "hk",
  "Macau": "mo",
  "Mongolia": "mn",
  "Kazakhstan": "kz",
  "Uzbekistan": "uz",
  "Kyrgyzstan": "kg",
  "Tajikistan": "tj",
  "Turkmenistan": "tm",
  "Afghanistan": "af",
  "Pakistan": "pk",
  "Bangladesh": "bd",
  "Sri Lanka": "lk",
  "Nepal": "np",
  "Bhutan": "bt",
  "Maldives": "mv",
  "Iran": "ir",
  "Iraq": "iq",
  "Syria": "sy",
  "Lebanon": "lb",
  "Jordan": "jo",
  "Palestine": "ps",
  "Saudi Arabia": "sa",
  "Yemen": "ye",
  "Oman": "om",
  "UAE": "ae",
  "Qatar": "qa",
  "Bahrain": "bh",
  "Kuwait": "kw",
  "Egypt": "eg",
  "Libya": "ly",
  "Tunisia": "tn",
  "Algeria": "dz",
  "Morocco": "ma",
  "Sudan": "sd",
  "South Sudan": "ss",
  "Ethiopia": "et",
  "Eritrea": "er",
  "Djibouti": "dj",
  "Somalia": "so",
  "Kenya": "ke",
  "Uganda": "ug",
  "Tanzania": "tz",
  "Rwanda": "rw",
  "Burundi": "bi",
  "Democratic Republic of the Congo": "cd",
  "Republic of the Congo": "cg",
  "Central African Republic": "cf",
  "Chad": "td",
  "Cameroon": "cm",
  "Equatorial Guinea": "gq",
  "Gabon": "ga",
  "São Tomé and Príncipe": "st",
  "Nigeria": "ng",
  "Niger": "ne",
  "Mali": "ml",
  "Burkina Faso": "bf",
  "Ivory Coast": "ci",
  "Ghana": "gh",
  "Togo": "tg",
  "Benin": "bj",
  "Liberia": "lr",
  "Sierra Leone": "sl",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Gambia": "gm",
  "Senegal": "sn",
  "Mauritania": "mr",
  "Cape Verde": "cv",
  "South Africa": "za",
  "Namibia": "na",
  "Botswana": "bw",
  "Zimbabwe": "zw",
  "Zambia": "zm",
  "Malawi": "mw",
  "Mozambique": "mz",
  "Madagascar": "mg",
  "Mauritius": "mu",
  "Seychelles": "sc",
  "Comoros": "km",
  "Lesotho": "ls",
  "Swaziland": "sz",
  "New Zealand": "nz",
  "Fiji": "fj",
  "Papua New Guinea": "pg",
  "Solomon Islands": "sb",
  "Vanuatu": "vu",
  "Samoa": "ws",
  "Tonga": "to",
  "Kiribati": "ki",
  "Tuvalu": "tv",
  "Nauru": "nr",
  "Palau": "pw",
  "Marshall Islands": "mh",
  "Micronesia": "fm"
};

const specialLogos: { [key: string]: string } = {
  "Europe": "https://upload.wikimedia.org/wikipedia/en/thumb/9/97/UEFA_logo.svg/1200px-UEFA_logo.svg.png",
  "World": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/FIFA_logo_without_slogan.svg/1200px-FIFA_logo_without_slogan.svg.png",
  "FIFA Club World Cup": "https://images.fotmob.com/image_resources/logo/leaguelogo/dark/78.png",
  "FIFA": "https://images.fotmob.com/image_resources/logo/leaguelogo/dark/78.png"
};

export const CountryFlag = ({ country, className }: CountryFlagProps) => {
  const specialLogo = specialLogos[country];

  if (specialLogo) {
    return (
      <Avatar className={className}>
        <AvatarImage src={specialLogo} alt={`${country} logo`} />
        <AvatarFallback>{country.slice(0, 2).toUpperCase()}</AvatarFallback>
      </Avatar>
    );
  }

  const code = countryCodeMapping[country]?.toLowerCase();
  const flagUrl = code ? `https://flagcdn.com/w40/${code}.png` : '';

  return (
    <Avatar className={className}>
      <AvatarImage src={flagUrl} alt={`${country} flag`} />
      <AvatarFallback>{country.slice(0, 2).toUpperCase()}</AvatarFallback>
    </Avatar>
  );
};
